name: Convert DEV Posts to Jekyll Markdown
#on:
 #schedule:
     # At midnight twice a week on Monday and Thursday
  #  - cron:  '0 0 * * 1,4'
on:
  issues:
    types: [opened, edited] 
jobs:
  dev-to-jekyll:
    runs-on: ubuntu-latest
    steps:
    - name: Check DEV and Update Jekyll Blog Posts
      uses: benhayehudi/dev-posts-to-jekyll-markdown-action@add-pr
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: New DEV Post To Blog Auto PR
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      DEV_API_KEY: "${{ secrets.DEV_API_KEY }}"
      NUM_OF_POSTS: "${{ secrets.NUM_OF_POSTS }}"